In [12]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
print(len(dir(np)))
print(np.__version__)

591
1.26.4


In [15]:
a = np.array(42) # 0D array
b = np.array([1, 2, 3, 4, 5]) # 1D array
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3D array
print(a)
print(b)
print(c)
print(d)


42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3 4]]
number of dimensions : 2


## **Indexing**

In [18]:
# Indexing in arrays

arr = np.array([1, 2, 3, 4])
print(arr[2])
print(arr[0] + arr[1])
# print(arr[2:])

3
3


In [19]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]
print('2nd element on 1st row: ', arr[0, 1])

SyntaxError: '(' was never closed (3451492358.py, line 1)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[-1, -1])

Last element from 2nd dim:  10


## **Slicing**

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

### **Positive Slicing**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


### **Negative Slicing**


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


### **Slicing 2D Arrays**

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.int16)
print(arr[1, 1:4])

[7 8 9]


In [ ]:
# confusing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## **DataType**

- `string`
- `integer`
- `float`
- `boolean`
- `complex`

Below is a list of all data types in NumPy and the characters used to represent them.

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void )

In [ ]:
arr1 = np.array([1, 2, 3, 50])
arr2 = np.array([1, 2, 3, 4000000000000])
print(arr1.dtype, arr2.dtype)

int32 int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


### **Creating Arrays With a Defined Data Type**

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
# arrc = np.array([1, 2, 3, 4], dtype='c')

print(arr)
print(arr.dtype)
# print(arrc)
# print(arrc.dtype)

TypeError: data type 'C' not understood

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### **Typecasting** 
using `astype`

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr = np.array([1,2,0,0,2])

newarr = arr.astype(bool)
print(newarr)
[print(i) for i in newarr]

[ True  True False False  True]
True
True
False
False
True


[None, None, None, None, None]

## **Copy array**

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr,'\n',x)

[42  2  3  4  5] 
 [1 2 3 4 5]


The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

*The view SHOULD be affected by the changes made to the original array.*

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

# changes x as well
arr[0] = 42
# changes arr as well
x[1] = 31

print(arr)
print(x)

[42 31  3  4  5]
[42 31  3  4  5]


### **Check if Array Owns its Data**
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

Copy returns `None` and view returns original data.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## **Shape**

The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### **Reshaping**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
# Error
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Error
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# newarr = arr.reshape(2, 3, -1)

#### **Reshape to 1D**

In [ ]:
arr = np.array([[[[1, 2, 3], [4, 5, 6]]]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### **NumPy Array Iterating**

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

print('\n')

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]


1
2
3
4
5
6


In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

for x in arr:
    print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


#### **Iterating Arrays Using `nditer()`**

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([1, 2, 3])

# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

print(arr[:, ::2])

1
3
5
7
[[1 3]
 [5 7]]


#### **Enumerated Iteration Using `ndenumerate()`**

In [ ]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)
  print(arr[idx], '\n')

(0, 0) 1
1 

(0, 1) 2
2 

(0, 2) 3
3 

(0, 3) 4
4 

(1, 0) 5
5 

(1, 1) 6
6 

(1, 2) 7
7 

(1, 3) 8
8 



## **Joining Array**

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

print(arr:=np.concatenate((arr1, arr2)), arr.shape)

[1 2 3 1 2 3] (6,)


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2))
print(arr)
ar = np.concatenate((arr1, arr2), axis=1)
ar

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
print(np.stack((arr1, arr2), axis=1))
print(np.stack((arr1, arr2), axis=0))
# print(np.stack((arr1, arr2), axis=2))


[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)
print(arr.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


## **Splitting Array**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

# Will give error once the array splitting is not possible
# narr = np.split(arr, 4)
# print(narr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## **Searching Arrays**

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the `where()` method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

NameError: name 'np' is not defined

In [ ]:
arr = np.array([1,2,3,4,5,6])
x = np.where(arr%2 == 0)
print(x)

NameError: name 'np' is not defined

## **Search Sorted**

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


## **Sort**

In [21]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [23]:
arr = np.array(['banana', 'cherry', 'apple', 'app'])
print(np.sort(arr))

['app' 'apple' 'banana' 'cherry']


In [24]:
# Possible reason - 0(False) then 1(True)  

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [25]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## **Filter**